baseurl: https://endearing-lebkuchen-4c34bc.netlify.app/
DefaultContentLanguage: en
title: Cody Leporini
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/cody.png
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: yes
  showRelatedPosts: yes
  socialShare: yes
  subtitle: Build a beautiful and simple website in minutes
  useHLJS: yes
  wordCount: yes
Author:
#this is the footer and where are the icons at the bottom are
  500px: username
  bandcamp: username
  bitbucket: username
  codepen: username
  email: codyleporini@icloud.com
  facebook: username
  github: username
  gitlab: username
  instagram: username
  itchio: username
  kaggle: username
  linkedin: https://www.linkedin.com/in/cody-leporini-699589236/
  mastodon: url
  name: Some Person
  paypal: username
  reddit: username
  slack: username
  snapchat: username
  soundcloud: username
  spotify: username
  stackoverflow: users/XXXXXXX/username
  telegram: username
  twitter: username
  vk: username
  website: yourwebsite.com
  weibo: username
  xing: username
  youtube: user/username
menu: 
#this is the nav bar settings
  main:
    - name: Blog 
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - identifier: samples
      name: Samples
      weight: 2
    - name: Big Image Sample
      parent: samples
      url: post/2017-03-07-bigimg-sample
      weight: 1
    - name: Math Sample
      parent: samples
      url: post/2017-03-05-math-sample
      weight: 2
    - name: Code Sample
      parent: samples
      url: post/2016-03-08-code-sample
      weight: 3
    - name: Tags
      url: tags
      weight: 3
