baseurl: https://endearing-lebkuchen-4c34bc.netlify.app/
DefaultContentLanguage: en
title: Cody Leporini
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/cody.png
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: yes
  showRelatedPosts: yes
  socialShare: yes
  subtitle: Statistician and Researcher
  useHLJS: yes
  wordCount: yes
Author:
#this is the footer and where are the icons at the bottom are
  email: codyleporini@icloud.com
  github: archerymaniac
  kaggle: username
  linkedin: cody-leporini-699589236/
  name: Cody Leporini
  website: yourwebsite.com
menu: 
#this is the nav bar settings
  main:
    - name: Blog 
      url: ''
      weight: 1
    - name: About
      url: page/about/
      weight: 3
    - identifier: samples
      name: Samples
      weight: 2
    - name: Big Image Sample
      parent: samples
      url: post/2017-03-07-bigimg-sample
      weight: 1
    - name: Math Sample
      parent: samples
      url: post/2017-03-05-math-sample
      weight: 2
    - name: Code Sample
      parent: samples
      url: post/2016-03-08-code-sample
      weight: 3
    - name: Tags
      url: tags
      weight: 3
